spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agricola
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-plataform: oorg.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update
