spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agricola
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-plataform: oorg.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

secret: 'Maecenas curabitur habitant integer dictumst porta vivamus, euismod quisque ante dictumst curabitur, senectus porttitor ipsum orci ornare. suscipit cras sit aenean malesuada porta, tellus est suspendisse hac elementum nec, torquent sociosqu litora augue. hac varius vivamus adipiscing nunc velit condimentum placerat maecenas eget, etiam porta metus conubia interdum eros scelerisque'
